using System;

namespace SODCustomStateInjectorMiami.Attributes
{
    /// <summary>
    ///     This attribute the generator method of a custom state.
    /// </summary>
    [AttributeUsage(AttributeTargets.Method)]
    public class GenerateStateAttribute : Attribute
    {
        public string StateName { get; }

        /// <summary>
        ///  Links a method to a state that is generated.
        /// </summary>
        /// <param name="stateName"> The name of the state that is generated by this method.</param>
        public GenerateStateAttribute(string stateName)
        {
            StateName = stateName;
        }
    }
}